# cspell: disable
name:                calc
author:              "Ben Wiedermann"

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README file

dependencies:
- base >= 4.7 && < 5
- cmdargs

spec-version: 0.36.0

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-export-lists
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fhide-source-paths
  - -freverse-errors

library:
  source-dirs: src
  dependencies:
    - array
  build-tools:
    - alex
    - happy

executables:
  calc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calc

tests:
  calc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calc
    - hspec
    - QuickCheck
